# Navigation Links
main:
  - name: Home
    url: /
    weight: 10
  - name: Projekte
    url: /#projekte
    weight: 20
  - name: Über uns
    url: /about/
    weight: 30
  - name: Kontakt
    url: /about/#kontakt
    weight: 40
